---
project_name: go-sse
builds:
  - main: ./cmd/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
release:
  github:
    owner: debug-ing
    name: go-sse